In [1]:
import numpy as np

In [4]:
lst = [11,15,65,42,97]
mt = np.array(lst)
print(mt)
print(type(mt))


[11 15 65 42 97]
<class 'numpy.ndarray'>


In [5]:
mtflot = np.array([1,2,3], dtype = np.float64)
print(mtflot)
print(type(mtflot))


[1. 2. 3.]
<class 'numpy.ndarray'>


In [7]:
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
mtflo = np.array([1.4, 3.6, -5.1, 9.42, 4.9999])
print(mtflo)

mtint = mtflo.astype(np.int32)
print(mtint)

[ 1.4     3.6    -5.1     9.42    4.9999]
[ 1  3 -5  9  4]


In [13]:
mt5 = np.array([2,5,67,9,6])
print(mt5)
mt6 = mt5.astype(np.float64)
print(mt6)

[ 2  5 67  9  6]
[ 2.  5. 67.  9.  6.]


In [16]:
mt7 = np.array([[25,10,9],[12,21,79],[61,22,69]])
print(mt7)

[[25 10  9]
 [12 21 79]
 [61 22 69]]


In [58]:
vazia = np.empty([3,2],dtype = int)
print(vazia)

[[       51317870               0]
 [139987172573552 139987172439632]
 [139987172523824 139987172415040]]


In [67]:
zerado = np.zeros([3,2])
print(zerado)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [70]:
un = np.ones([3,2])
print(un)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [77]:
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [108]:
aleatorio = np.random.randint(20)
print(aleatorio)

8


In [111]:
ale2 = np.random.randn(5)
print(ale2)

[ 0.77122167  1.53895288 -1.06020526 -2.061082    1.48722923]


In [119]:
ale3 = (10*np.random.random((3,4)))
print(ale3)
ale3Int = ale3.astype(int)
print(ale3Int)

[[6.04432743 4.28456985 3.74994252 9.61431987]
 [5.45114043 5.77602538 8.83557645 6.3179066 ]
 [9.55761552 1.00293074 7.10031311 8.66838656]]
[[6 4 3 9]
 [5 5 8 6]
 [9 1 7 8]]


In [203]:
ale4 = np.random.default_rng(1)
ale5 = ale4.random(3)
print(ale4)
print(ale5)

Generator(PCG64)
[0.51182162 0.9504637  0.14415961]


In [204]:
ale6 = ale4.integers(10, size=(3,4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [205]:
orga = np.array([12,13,13,14,15,7,78,76,66,6,6,5,44,4,3,10])
orga = np.unique(orga)
print(orga)

[ 3  4  5  6  7 10 12 13 14 15 44 66 76 78]


In [208]:
k = np.array([[12,15,18],[11,14,10],[9,5,40]])
print(k.shape)

(3, 3)


In [221]:
raiz =  [36,25,81,49,144,100]
print(np.sqrt(raiz))

[ 6.  5.  9.  7. 12. 10.]


In [223]:
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,9]])
print(n+o)

[[ 2  3]
 [ 4 13]]


In [228]:
s = np.array(([2,3],[6,1],[8,2]))
r = np.array(([4,5]))
print(s*r)

[[ 8 15]
 [24  5]
 [32 10]]


In [248]:
sudoku = np.arange(9).reshape(3,3)
print(sudoku)

su = sudoku.T
print(su)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [250]:
x = (su >=5)
print(x)

[[False False  True]
 [False False  True]
 [False  True  True]]


In [254]:
y = np.where(sudoku % 2 == 0, 0, 1)
print(y)

[[0 1 0]
 [1 0 1]
 [0 1 0]]
